MODEL_URL: "https://tfhub.dev/google/movenet/singlepose/lightning/4"
FRAME_SKIP: 15
CONFIDENCE_THRESHOLD: 0.5
WINDOW_NAME: "MoveNet Motion Tracking"
ACTIVITY_HISTORY_SIZE: 30
LOG_LEVEL: "INFO"

# Activity detection parameters
STANDING_THRESHOLD: 0.15
SITTING_THRESHOLD: 0.15
RAISING_HANDS_THRESHOLD: 0.2
JUMPING_THRESHOLD: 0.25
RUNNING_THRESHOLD: 0.2
WALKING_THRESHOLD: 0.15

# New activity thresholds
TYPING_THRESHOLD: 0.15
WAVING_THRESHOLD: 0.2
CLAPPING_THRESHOLD: 0.2

# Performance settings
ENABLE_GPU: true
FRAME_BUFFER_SIZE: 2
SMOOTHING_WINDOW: 5

# Performance optimizations
ENABLE_THREADING: true
THREAD_POOL_SIZE: 4
MODEL_QUANTIZATION: true
BATCH_PROCESSING: true
BATCH_SIZE: 4

# Visualization settings
SHOW_CONFIDENCE: true
SHOW_SKELETON: true
SKELETON_COLOR: [0, 255, 0]
JOINT_COLOR: [255, 0, 0]
